# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-15 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotVersionManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionRunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionname', models.CharField(max_length=32)),
                ('versionpath', models.CharField(max_length=64)),
                ('ispull', models.CharField(max_length=32, null=True)),
                ('isrun', models.CharField(max_length=32, null=True)),
                ('iscloudtest', models.CharField(max_length=32, null=True)),
                ('iscloudtestrun', models.CharField(max_length=32, null=True)),
                ('cloudtest_result', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='versionrecord',
            name='otherinfo',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
